# Generated by Django 4.0.5 on 2022-07-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'Themes',
            },
        ),
        migrations.AlterModelTable(
            name='article',
            table='Articles',
        ),
        migrations.CreateModel(
            name='ArticleScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.theme')),
            ],
            options={
                'db_table': 'articles and themes',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.theme'),
        ),
    ]
