# Generated by Django 4.0.5 on 2022-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_id_alter_phone_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterModelTable(
            name='phone',
            table=None,
        ),
    ]
